### ISSUE TITLE
Tests are not working

### ISSUE THREAD

**Issue by joergfunger** [BAMresearch/ModelCalibration#24]
The tests are not working. The recently changed tests are not integrated into the github actions. I have added a branch correct_unique_conda_environment that creates a single environment for all steps to be used (conda create -f environment.yml). This is then also added in the actions.

**Comment by eriktamsen** [comment]
Its possible that the failure of the FEM test has nothing to do with the changes in this repo. I fear there is some outside dependency that has changed. Annika and I have the same problem within the fenics concrete repostory.
